---
.rubocop.yml:
  default_configs:
    AllCops:
      NewCops: enable
.pdkignore:
  paths:
    - /.*.yml
    - /pdk.yaml
    - /.pmtignore
    - /.git*
    - /.editorconfig
    - /provision.yaml
Rakefile:
  default_disabled_lint_checks:
    - '140chars'
spec/spec_helper.rb:
  coverage_report: true
  minimum_code_coverage_percentage: 100
