name: "ci"

on:
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - '**.md'
      - 'examples/**'
      - 'LICENSE'
      - 'CODEOWNERS'
      - 'AUTHORS'
  workflow_dispatch:

jobs:
  Spec:
    uses: "./.github/workflows/module_ci.yml"
    secrets: "inherit"

  Acceptance:
    needs: Spec
    uses: "puppetlabs/cat-github-actions/.github/workflows/module_acceptance.yml@main"
    secrets: "inherit"
    with:
      runs_on: "ubuntu-20.04"
