name: ci

on:
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - '**.md'
      - 'examples/**'
      - 'LICENSE'
      - 'CODEOWNERS'
      - 'AUTHORS'
  workflow_dispatch:
    inputs:
      run_spec:
        description: "Run Spec job"
        type: boolean
        required: false
        default: true
      run_acceptance:
        description: "Run Acceptance job"
        type: boolean
        required: false
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Matrix:
    uses: ./.github/workflows/module_matrix.yml
    with:
      runs_on: "ubuntu-20.04"
      flags: "--exclude-platforms '[\"Ubuntu-18.04\"]'"
  Spec:
    if: ${{ github.event_name == 'pull_request' || inputs.run_spec == 'true' }}
    strategy:
      matrix: ${{ fromJson(needs.Matrix.outputs.spec_matrix) }}
    needs: Matrix
    uses: ./.github/workflows/module_ci.yml
    secrets: inherit
  Acceptance:
    needs: Matrix
    strategy:
      matrix: ${{ fromJson(needs.Matrix.outputs.spec_matrix) }}
    if: ${{ inputs.run_matrix == 'true' }}
    uses: "./.github/workflows/module_acceptance.yml"
    secrets: "inherit"
