name: "ci"

on:
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - '**.md'
      - 'examples/**'
      - 'LICENSE'
      - 'CODEOWNERS'
      - 'AUTHORS'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Acceptance:
    uses: "./.github/workflows/module_acceptance.yml"
    secrets: "inherit"
    with:
      flags: "--exclude-platforms '[\"ubuntu-18.04\",\"Scientific-7\",\"CentOS-7\",\"OracleLinux-7\"]'" # EL7 is failing on GHA, ubuntu 18 module updates
