name: "ci"

on:
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - '**.md'
      - 'examples/**'
      - 'LICENSE'
      - 'CODEOWNERS'
      - 'AUTHORS'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Spec:
    uses: ./.github/workflows/module_ci.yml
    secrets: inherit
  Acceptance:
    uses: "./.github/workflows/module_acceptance.yml"
    secrets: "inherit"
    with:
      flags: "--exclude-platforms '[\"Ubuntu-18\",\"CentOS-7\",\"OracleLinux-7\"]'"
